### ISSUE TITLE
Heroku Deployment Fail: npm WARN checkPermissions Missing write access 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#22]
While attempting to deploy this app to Heroku, we are seeing the following error:
```
-----> Building dependencies
       Installing and caching node modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! invalid bin entry for package @babel/parser@7.8.4. key=parser, value=bin/babel-parser.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2020-03-01T00_22_53_264Z-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed
```

**Comment by nelsonic** [comment]
https://dashboard.heroku.com/apps/phemail/activity/builds/1a6308aa-4f19-4b71-b232-d932efa38c24
![image](https://user-images.githubusercontent.com/194400/75617792-db712b80-5b5b-11ea-9ce8-d3e85e675c45.png)

**Comment by nelsonic** [comment]
https://stackoverflow.com/questions/15560037/heroku-troubleshooting-npm-errors-during-deploy-reading-a-tmp-file > https://devcenter.heroku.com/articles/troubleshooting-node-deploys

**Comment by nelsonic** [comment]
Known issue reported by @samhstn https://github.com/npm/cli/issues/613 💭

**Comment by nelsonic** [comment]
```
Downloading and installing node 12.16.1...
       Installing Node 12.16.1...
       Downloading and installing npm 6.13.7 (replacing version 6.13.4)...
```
This is promising ...

**Comment by nelsonic** [comment]
Spoke too soon ...
```
npm timing npm Completed in 3531ms
npm info ok 
       npm WARN checkPermissions Missing write access to /tmp/build_25f399ac5fbb0663d2f70dd175733106/assets/node_modules/phoenix
       npm WARN checkPermissions Missing write access to /tmp/build_25f399ac5fbb0663d2f70dd175733106/assets/node_modules/phoenix_html
       npm ERR! code ENOENT
       npm ERR! syscall access
       npm ERR! path /tmp/build_25f399ac5fbb0663d2f70dd175733106/assets/node_modules/phoenix
       npm ERR! errno -2
       npm ERR! enoent ENOENT: no such file or directory, access '/tmp/build_25f399ac5fbb0663d2f70dd175733106/assets/node_modules/phoenix'
       npm ERR! enoent This is related to npm not being able to find a file.
       npm ERR! enoent
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2020-03-01T02_03_35_880Z-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed

```

**Comment by nelsonic** [comment]
I'm losing the will ... https://dashboard.heroku.com/apps/phemail/activity/builds/346537d3-9312-46c7-aec8-1d229c7aa01d
![image](https://user-images.githubusercontent.com/194400/75618186-88e73d80-5b62-11ea-85f7-3ff24fbe0226.png)

```
       npm WARN checkPermissions Missing write access to /tmp/build_f9de20f9568fdb6885359dc1065e7edf/assets/node_modules/phoenix
       npm WARN checkPermissions Missing write access to /tmp/build_f9de20f9568fdb6885359dc1065e7edf/assets/node_modules/phoenix_html
       npm ERR! code ENOENT
       npm ERR! syscall access
       npm ERR! path /tmp/build_f9de20f9568fdb6885359dc1065e7edf/assets/node_modules/phoenix
       npm ERR! errno -2
       npm ERR! enoent ENOENT: no such file or directory, access '/tmp/build_f9de20f9568fdb6885359dc1065e7edf/assets/node_modules/phoenix'
       npm ERR! enoent This is related to npm not being able to find a file.
       npm ERR! enoent
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2020-03-01T02_14_22_548Z-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed
```

Why would NPM not have access to this file?!

**Comment by nelsonic** [comment]
https://elixirforum.com/t/heroku-deploy-issues-with-phoenix-1-3/5710 instructs to add:
```
assets_path=assets
phoenix_ex=phx
```
To the `phoenix_static_buildpack.config` file ... trying that now.

**Comment by nelsonic** [comment]
```
npm ERR! enoent ENOENT: no such file or directory, access 'assets/node_modules/phoenix'
```

According to: https://github.com/geolessel/react-phoenix/issues/35#issuecomment-504286846
Deleting the `package-lock.json` file and `npm install` again might do the trick ...

**Comment by nelsonic** [comment]
After reading https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/55#issuecomment-277951400 
I discovered that the _order_ of the build packs _matters_ ... 🙄 

Before:
![image](https://user-images.githubusercontent.com/194400/75618398-95b96080-5b65-11ea-830e-8cb72c58c9aa.png)
After:
![image](https://user-images.githubusercontent.com/194400/75618400-a8339a00-5b65-11ea-9707-8f46730f4912.png)

# `#FFS` 3 _Hours_ Later...! 🤦‍♂ 

At least the deployment works ...

**Comment by btrd** [comment]
I just had the exact same issue on another project, I also had to add this to the `phoenix_static_buildpack.config` file :

`npm_version=6.14.4`

**Comment by nelsonic** [comment]
@btrd thanks for sharing. 🥇

**Comment by SolbiatiAlessandro** [comment]
> After reading [gjaldon/heroku-buildpack-phoenix-static#55 (comment)](https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/55#issuecomment-277951400)
> I discovered that the _order_ of the build packs _matters_ ... 🙄
> 
> Before:
> ![image](https://user-images.githubusercontent.com/194400/75618398-95b96080-5b65-11ea-830e-8cb72c58c9aa.png)
> After:
> ![image](https://user-images.githubusercontent.com/194400/75618400-a8339a00-5b65-11ea-9707-8f46730f4912.png)
> 
> # `#FFS` 3 _Hours_ Later...! 🤦‍♂
> At least the deployment works ...
> 
> ![image](https://user-images.githubusercontent.com/194400/75618442-70792200-5b66-11ea-9eb0-f0bc674303ef.png)

worked for me, fixed the issue in just 2 mins thanks so much <3
