### ISSUE TITLE
Add "Send Test Email To Myself" Buttton

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#7]
Add ability to test the functionality by sending a test email to myself...

**Comment by iteles** [comment]
:ok_hand: Good idea!

**Comment by nelsonic** [comment]
Made a quick video of the demo: https://youtu.be/yflPSotYd9Y

![send-email-dashboard-test](https://user-images.githubusercontent.com/194400/77336873-0d6f4b00-6d20-11ea-8cb1-510d22a69385.gif)


Open the Dashboard: https://phemail.herokuapp.com
Click on the "Send Test Email" in a new window: https://phemail.herokuapp.com/sent/new
![image](https://user-images.githubusercontent.com/194400/77308978-beabbc00-6cf3-11ea-8bb5-70425ffef6b9.png)

Try sending an email to a _real_ email address e.g: `nelson+heroku.test@dwyl.com`

### Simulate a _Bounce_

Try it with the bounce simulator: `bounce@simulator.amazonses.com`
![image](https://user-images.githubusercontent.com/194400/77310980-2adbef00-6cf7-11ea-8a1a-dd599b65ee9e.png)

When the bounce SNS notification comes in, you should see it at the top of the table:
![image](https://user-images.githubusercontent.com/194400/77337099-5a532180-6d20-11ea-99cd-2315f2f0f1f3.png)

**Comment by iteles** [comment]
Tested this morning and working exactly as per the videos above 🙌
